### ISSUE TITLE
Web interface allowing to upload a jar to the current Amazon instance

### ISSUE THREAD

**Issue by PawelLipski** [tilius/amazon-scala-paas#2]

**Comment by BartoszJanota** [comment]
Play Framework?

**Comment by PawelLipski** [comment]
Sure, seems legit. Let's keep it uberminimal.

2015-04-25 10:27 GMT+02:00 Bartosz Janota notifications@github.com:

**Comment by BartoszJanota** [comment]
Cannot see any other opportunities, or maybe I'm wrong, any ideas guys?
It will be deployed as an autonomous service, yep? And than it will be able to communicate with each VM via what? 
Or maybe we don't need such a big framework as Play. Maybe REST API (Spray or Akka HTTP) exposed at each node + angular.js as an autonomous application?

**Comment by PawelLipski** [comment]
Yep, it's an autonomous service, but anyway we may like to deploy the
webapp to one of the two Amazon nodes having a public IP (aka the master
node).
Once the jar is uploaded to the master, it's simply copied and launched at
the other machines via their private IPs. We can go for raw scp/ssh, do it
Ansible-wise (Supervisor etc.) or pass the files/commands around via HTTP.
I'd rather pick the third option. It'd be clean to stick to HTTP
everywhere. Maybe expect for setting up the machines, which I already coded
up in Ansible.
You said "REST API exposed at each node". I believe we rather want a
browser-visible REST API at the master node and a master-visible REST API
at each slave.
As a matter of detail, the master (webapp) node can as well host a running
slave service.
angular.js for the front-end seems cool, anybody besides Bartek
familiar/willing to learn?

2015-04-26 15:23 GMT-03:00 Bartosz Janota notifications@github.com:

**Comment by BartoszJanota** [comment]
I'm not familiar with and dont't want to learn :)!
