### ISSUE TITLE
Run an uploaded jar - figure out how to do that for SIUS/SZiA

### ISSUE THREAD

**Issue by PawelLipski** [tilius/amazon-scala-paas#3]

**Comment by BartoszJanota** [comment]
java -jar ... :P?

**Comment by aksiazek** [comment]
Ansible add openjdk packages more like I think?

W dniu 25.04.2015 o 10:25, Bartosz Janota pisze:

**Comment by BartoszJanota** [comment]
Sure :), do you know Supervisor?

**Comment by aksiazek** [comment]
A first to me, I assume you mean this: https://docs.ansible.com/supervisorctl_module.html
Looks like an abstraction over such mechanisms as /etc/init.d/ star/stop scripts or services, correct?

**Comment by BartoszJanota** [comment]
Yep, this is very friendly and easy to use. With supervisorctl you can simply manage your own services. Do not know if Supervisor is a module within Ansible or something. I was using it as an autonomous program.

**Comment by PawelLipski** [comment]
Alek, this ticket includes figuring out the launch/shutdown API for SZiA
(defining a setUp/tearDown method and so on). It's still kinda little one,
so please also cook up a architecture doc with diagrams for next SIUS labs
(as pointed out in the yesterday's email).

I baked the Supervisor stuff into my Ansible ticket (
https://github.com/tilius/amazon-scala-paas/issues/4).

2015-04-25 11:51 GMT+02:00 Bartosz Janota notifications@github.com:

**Comment by aksiazek** [comment]
Ticket closed as not-well-defined.
