### ISSUE TITLE
Sort out jar deploy (scp/AWScala?)

### ISSUE THREAD

**Issue by PawelLipski** [tilius/amazon-scala-paas#6]
Rozwiązanie na odwal - hardkodujemy gdzieś pulę prywatnych IPków maszyn (stawiamy i włączamy je ręcznie, kiedy trzeba) i scpujemy na nie te jary. Ładnie - używamy do stawiania/włączania maszyn i wrzucania na nie kodu jakiegoś ładnego API dla Amazona. Typu Boto (Python) co Bartek polecał albo czegoś podobnego dla Scali.

**Comment by BartoszJanota** [comment]
I can see two ways of jar upload: 
- jar can be sent directly to the given VM via scp like method 
- jar can be uploaded to the s3 bucket and downloaded to the VM instance then
  Does not matter which way we choose we are not able to avoid a shell script to be run on VM.
  Any other ideas?

Fuck, napisałem to po angyelskiemu i w momencie klikania na comment zobaczyłem to co napisałeś wyżej :D, stawiać/włączać maszyn z kodu raczej się nie da.
